controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


forward_position_controller:
  ros__parameters:
    joints:
      - X_Axis_Joint
    interface_name: position

